---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.2.0
    driver_config:
      customize:
        memory: 1024
        cpus: 1

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[pbuilder::default]
    attributes:
      pbuilder:
        chroots:
          wheezy64:
            distribution: wheezy
            architecture: amd64
            debootstrapopts:
              - --variant=buildd
